server:
  port: 7001
  shutdown: graceful

debug: false

logging:
  config: classpath:log4j2-sink.xml

spring:
  application:
    name: DATACHECKER-EXTRACT-${spring.extract.endpoint}
  lifecycle:
    timeout-per-shutdown-phase: 5
  extract:
    schema: jack  # 宿端数据实例
    databaseType: OG  # 宿端数据库类型 OG opengauss
    endpoint: SINK   # 宿端端点类型
    debezium-enable: false #是否开启增量debezium配置 默认不开启
    sync-extract: true

  datasource:
    druid:
      dataSourceOne:
        driver-class-name: org.opengauss.Driver
        url: jdbc:opengauss://xxxxx:xxx/xxxx?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: xxxxx
        password: xxxxxxxx
        type: com.alibaba.druid.pool.DruidDataSource
        #Spring Boot 默认是不注入这些属性值的，需要自己绑定
        #druid 数据源专有配置
        initialSize: 50
        minIdle: 5
        maxActive: 200
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        #validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true

        #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
        #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
        #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

