server:
  port: 9001
  shutdown: graceful

debug: false

logging:
  config: classpath:log4j2-sink.xml

spring:
  application:
    name: DATACHECKER-EXTRACT-${spring.extract.endpoint}
  lifecycle:
    timeout-per-shutdown-phase: 5
  extract:
    schema: jack
    databaseType: OG  #OG opengauss
    endpoint: SINK
    debezium-enable: false
    sync-extract: true

  datasource:
    druid:
      dataSourceOne:
        driver-class-name: org.opengauss.Driver
        url: jdbc:opengauss://xxxxx:xxx/xxxx?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: xxxxx
        password: xxxxxxxx
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 50
        minIdle: 5
        maxActive: 200
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true

      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

