server:
  port: 9000
  shutdown: graceful

debug: false

spring:
  application:
    name: datachecker-check
  lifecycle:
    timeout-per-shutdown-phase: 5
  kafka:
    consumer:
      group-id: checkgroup
      enable-auto-commit: true
      auto-commit-interval: 100
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      fetch-min-size: 1
      max-poll-records: 10000

  datasource:
    druid:
      dataCheck:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


feign:
  okhttp:
    enabled: true

logging:
  config: classpath:log4j2.xml

data:
  check:
    data-path: local_path/xxx
    bucket-expect-capacity: 10
    health-check-api: /extract/health
    black-white-mode: BLACK
    # statistical-enable : Configure whether to perform verification time statistics.
    # If true, the execution time of the verification process will be statistically analyzed automatically.
    statistical-enable: false
    # auto-clean-environment： Configure whether to automatically clean the execution environment.
    # If set to true, the environment will be cleaned automatically after the full verification process is completed.
    auto-clean-environment: true
    check-with-sync-extracting: true
    retry-fetch-record-times: 5




