server:
  port: 9000
spring:
  kafka:
    bootstrap-servers: { ip }:{port};{ip}:{port}
data:
  check:
    data-path: local_path/xxx
    source-uri: http://{ip}:{port} #  server.port=9001
    sink-uri: http://{ip}:{port} # server.port=9002
    # Configure the black and white list startup mode of the checklist
    # [black starts the black list verification,white starts the white list verification]
    black-white-mode: BLACK




