server:
  port: 9002
spring:
  check:
    server-uri: http://127.0.0.1:9000
  extract:
    schema: jack
    databaseType: OG
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    druid:
      dataSourceOne:
        driver-class-name: org.opengauss.Driver
        url: jdbc:opengauss://127.0.0.1:5432/postgres?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username:
        password: 'xxxx'  # The password text may contain special characters, which need to be enclosed in quotation marks