server:
  port: 9002

debug: false

spring:
  check:
    server-uri: http://{ip}:{port}
  extract:
    schema: test
    databaseType: MS
    debezium-enable: false
    debezium-time-period: 1 # Debezium incremental migration verification time period: 24 * 60 unit: Min
    # debezium-num-period: Debezium incremental migration verification is the threshold value of the number
    # of incremental change records. The default value is 1000. The threshold value should be greater than 100
    debezium-num-period: 1000

  kafka:
    bootstrap-servers: { ip }:{port};{ip}:{port}
  datasource:
    druid:
      dataSourceOne:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://{ip}:{port}/{database}?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username:
        password: