server:
  port: 9002
logging:
  config: # absolute_path/log4j2sink.xml
spring:
  check:
    server-uri: http://127.0.0.1:9000
  extract:
    schema: jack
    databaseType: OG
    query-dop: 8 # openGauss database Parallel Query session config
    debezium-enable: false # no need config,but not delete
    debezium-topic:  # no need config,but not delete
    debezium-groupId: # no need config,but not delete
    debezium-time-period: 1 # no need config,but not delete
    debezium-num-period: 1000 # no need config,but not delete
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    druid:
      dataSourceOne:
        driver-class-name: org.opengauss.Driver
        url: jdbc:opengauss://127.0.0.1:5432/postgres?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username:
        password: 'xxxx'  # The password text may contain special characters, which need to be enclosed in quotation marks