server:
  port: 9000

debug: false

spring:
  datasource:
    druid:
      dataCheck:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://{ip}:{port}/check?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username:
        password:
  kafka:
    bootstrap-servers: { ip }:{port};{ip}:{port}
data:
  check:
    data-path: local_path/xxx
    source-uri: http://{ip}:{port} #  server.port=9001
    sink-uri: http://{ip}:{port} # server.port=9002
    # Configure the black and white list startup mode of the checklist
    # [black starts the black list verification,white starts the white list verification]
    black-white-mode: BLACK




