server:
  port: 9001

debug: false

spring:
  check:
    server-uri: http://{ip}:{port}
  extract:
    schema: jack
    databaseType: OG
  kafka:
    bootstrap-servers: { ip }:{port};{ip}:{port}
  datasource:
    druid:
      dataSourceOne:
        driver-class-name: org.opengauss.Driver
        url: jdbc:opengauss://{ip}:{port}/{schema_db}?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username:
        password: